
name: CI Windows

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
        architecture: [Win32, x64]
        build_type: [Debug, Release]
        cxx_standard: [11, 14, 17, 20]
    steps:
    - uses: actions/checkout@v2
    
    - name: Update Submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
            -A ${{matrix.architecture}}
            -DSAMPLES_BUILD=ON
            -DSAMPLES_BUILD_ONLY_DYNAMIC=ON
            -DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON
            -DTESTS_BUILD=ON
            -DTESTS_BUILD_ONLY_DYNAMIC=ON
            -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON
            -DVULKAN_HPP_RUN_GENERATOR=ON
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}}
            
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
